/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.prosport.view;

/**
 *
 * @author Rusith
 */
public class POSTransactionView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(POSTransactionView.class.getName());

    /**
     * Creates new form POSTransactionView
     */
    public POSTransactionView() {
        initComponents();
        setLocationRelativeTo(null);
        loadCustomers();
    }
    
    private void loadCustomers() {
    try (java.sql.Connection conn = com.prosport.config.DBConnection.getInstance().getConnection();
         java.sql.Statement stmt = conn.createStatement();
         java.sql.ResultSet rs = stmt.executeQuery("SELECT full_name FROM customers")) {
        
        cmbCustomers.removeAllItems();
        cmbCustomers.addItem("-- Select Customer --");
        while (rs.next()) {
            cmbCustomers.addItem(rs.getString("full_name"));
        }
    } catch (Exception e) {
        // If table doesn't exist yet, keep default items
    }
}
    
    private void calculateTotal() {
    double total = 0.0;
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblCart.getModel();
    for (int i = 0; i < model.getRowCount(); i++) {
        double subtotal = Double.parseDouble(model.getValueAt(i, 4).toString());
        total += subtotal;
    }
    lblTotalAmount.setText(String.format("Total: %.2f", total));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSearchBarcode = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        btnAddToCart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        cmbCustomers = new javax.swing.JComboBox<>();
        lblTotalAmount = new javax.swing.JLabel();
        btnRemoveItem = new javax.swing.JButton();
        btnClearCart = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ProSport - POS Billing & Checkout Terminal");
        setPreferredSize(new java.awt.Dimension(950, 650));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("POS BILLING & CHECKOUT TERMINAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(239, 239, 239))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(33, 33, 33))
        );

        jLabel2.setText("Barcode: ");

        jLabel3.setText("Quantity: ");

        btnAddToCart.setText("Add to Cart");
        btnAddToCart.addActionListener(this::btnAddToCartActionPerformed);

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Product Name", "Unit Price", "Qty", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblCart);

        jLabel4.setText("Customer Select: ");

        cmbCustomers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTotalAmount.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTotalAmount.setText("Total: 0.00 ");

        btnRemoveItem.setText("Remove Item");
        btnRemoveItem.addActionListener(this::btnRemoveItemActionPerformed);

        btnClearCart.setText("Clear Cart");
        btnClearCart.addActionListener(this::btnClearCartActionPerformed);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Process Sale & Print Bill ");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(159, 159, 159)
                                .addComponent(btnAddToCart))
                            .addComponent(txtSearchBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(41, 41, 41)
                                .addComponent(cmbCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTotalAmount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 325, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRemoveItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClearCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddToCart))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveItem))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalAmount)
                    .addComponent(btnClearCart))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        String barcode = txtSearchBarcode.getText().trim();
    String qtyStr = txtQuantity.getText().trim();

    if (barcode.isEmpty() || qtyStr.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter Barcode and Quantity.");
        return;
    }

    try {
        int requestedQty = Integer.parseInt(qtyStr);
        if (requestedQty <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Quantity must be greater than 0.");
            return;
        }

        java.sql.Connection conn = com.prosport.config.DBConnection.getInstance().getConnection();
        java.sql.PreparedStatement pstmt = conn.prepareStatement("SELECT * FROM products WHERE barcode = ?");
        pstmt.setString(1, barcode);
        java.sql.ResultSet rs = pstmt.executeQuery();

        if (rs.next()) {
            int productId = rs.getInt("product_id");
            String productName = rs.getString("product_name");
            double unitPrice = rs.getDouble("unit_price");
            int stock = rs.getInt("stock_quantity");

            if (requestedQty > stock) {
                javax.swing.JOptionPane.showMessageDialog(this, "Insufficient stock! Available in database: " + stock);
                return;
            }

            double subtotal = unitPrice * requestedQty;

            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblCart.getModel();
            model.addRow(new Object[]{productId, productName, unitPrice, requestedQty, subtotal});

            calculateTotal();
            txtSearchBarcode.setText("");
            txtQuantity.setText("1");
            txtSearchBarcode.requestFocus();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Product not found for Barcode: " + barcode);
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid numeric quantity.");
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error adding item: " + e.getMessage());
    }
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void btnRemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveItemActionPerformed
        int selectedRow = tblCart.getSelectedRow();
    if (selectedRow != -1) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblCart.getModel();
        model.removeRow(selectedRow);
        calculateTotal();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select an item from the cart table to remove.");
    }
    }//GEN-LAST:event_btnRemoveItemActionPerformed

    private void btnClearCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCartActionPerformed
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblCart.getModel();
        model.setRowCount(0);
        calculateTotal();
    }//GEN-LAST:event_btnClearCartActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblCart.getModel();
    if (model.getRowCount() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Cart is empty. Add items before processing checkout.");
        return;
    }

    try (java.sql.Connection conn = com.prosport.config.DBConnection.getInstance().getConnection()) {
        conn.setAutoCommit(false); // Begin SQL transaction block

        // 1. Calculate Total Amount
        String totalText = lblTotalAmount.getText().replaceAll("[^0-9.]", "");
        double totalAmount = Double.parseDouble(totalText);

        // 2. Insert Record into Sales Table
        java.sql.PreparedStatement stmtSale = conn.prepareStatement(
            "INSERT INTO sales (total_amount) VALUES (?)",
            java.sql.Statement.RETURN_GENERATED_KEYS
        );
        stmtSale.setDouble(1, totalAmount);
        stmtSale.executeUpdate();

        // 3. Update Inventory Stock for Each Item
        java.sql.PreparedStatement stmtStock = conn.prepareStatement(
            "UPDATE products SET stock_quantity = stock_quantity - ? WHERE product_id = ?"
        );

        for (int i = 0; i < model.getRowCount(); i++) {
            int productId = Integer.parseInt(model.getValueAt(i, 0).toString());
            int qty = Integer.parseInt(model.getValueAt(i, 3).toString());

            stmtStock.setInt(1, qty);
            stmtStock.setInt(2, productId);
            stmtStock.addBatch();
        }
        stmtStock.executeBatch();

        conn.commit(); // Commit database transaction
        conn.setAutoCommit(true);

        javax.swing.JOptionPane.showMessageDialog(this, "Transaction completed successfully!");

        // Reset cart table
        model.setRowCount(0);
        calculateTotal();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Checkout Failed: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new POSTransactionView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnClearCart;
    private javax.swing.JButton btnRemoveItem;
    private javax.swing.JComboBox<String> cmbCustomers;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JTable tblCart;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearchBarcode;
    // End of variables declaration//GEN-END:variables
}
